CK_TWITTER = 'TTKmfnSiBFe5souT2ptWaA'
CS_TWITTER = 'kEUxVm1v2P0bpnJLUrGTjamBQtvy25vCgHg4deYo'

CK_FOURSQUARE = 'TYZMZVK5UODORNIZTOOTQC4JXA1OL1QPQDSABGMB1ZTWZHR4'
CS_FOURSQUARE = '3VJ30SFI0EO1AFGAERWVM2002FGQYRUKRR1MUN1DPD2EPSCS'

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :twitter, CK_TWITTER , CK_TWITTER
  provider :foursquare, CK_FOURSQUARE, CS_FOURSQUARE 
end